#!/usr/bin/env node
const DIST_DIR = "dist";
import fs from "fs";
import path from "path";
import sharp from "sharp";
import { DOMParser } from "@xmldom/xmldom";
const allProjects = JSON.parse(fs.readFileSync("./projects.json"));
let document;
let skipImages = process.argv.includes("--skip-images");

if (skipImages) {
	process.argv.splice(process.argv.indexOf("--skip-images"), 1);
}

if (process.argv.length > 2) {
	for (let i = 2; i < process.argv.length; i++) {
		await processProjectName(process.argv[i]);
	}
} else for (const projectName of allProjects) {
	await processProjectName(projectName);
}

async function processProjectName(projectName) {
	console.log(`Processing ${projectName}.`);
	if (!fs.existsSync(`../projects/${projectName}`)) {
		console.error(`Project ${projectName} does not exist!`);
		return;
	}
	const projectData = JSON.parse(fs.readFileSync(`../projects/${projectName}/info.json`));
	const distPath = path.join(import.meta.dirname, "..", projectData.root, DIST_DIR);
	if (fs.existsSync(distPath) && !skipImages) fs.rmSync(distPath, { recursive: true, force: true });
	await buildProjectPage(projectData);
}

async function buildProjectPage(project) {
	const root = path.join(import.meta.dirname, "..", project.root);
	const htmlPath = path.join(root, "index.html");
	const currentDatetime = new Date();
	let htmlSource = "";
	htmlSource += generateHTMLComment(`This file was generated by generateStaticPages.js at ${currentDatetime}. Do not edit.`) + "\n";
	htmlSource += `<!DOCTYPE html><html><head></head><body></body></html>`;
	document = new DOMParser().parseFromString(htmlSource, "text/html");
	document.documentElement.setAttribute("lang", "ru");
	await insertHeadTags(document, project);
	await insertBodyTags(document, project);
	htmlSource = document.toString();
	fs.writeFileSync(htmlPath, htmlSource);
	// console.log(document.toString());
	console.log(`Written ${htmlSource.length} characters to ${htmlPath}.`);
}

function generateHTMLComment(commentText) {
	return `<!-- ${commentText} -->`;
}

async function insertHeadTags(document, project) {
	// optimizeImage(root, projectRoot, image, quality, sizes)
	const optimizedPreviewImage = await optimizeImage(
		project.root,
		project.root,
		project.previewImage.replace(project.root, "").replace(/^\//, ""),
		80,
		[]
	);
	console.log(optimizedPreviewImage.converted);
	const metaTags = [
		{ "charset": "utf-8" },
		{ "name": "viewport", "content": "width=device-width, initial-scale=1.0" },
		{ "name": "title", "content": project.title },
		{ "name": "og:title", "content": project.title },
		{ "name": "og:type", "content": "website" },
		{ "name": "og:image", "content": optimizedPreviewImage.converted },
		{ "name": "twitter:card", "content": "summary_large_image" },
	];

	const head = document.getElementsByTagName("head")[0];
	for (let i = 0; i < metaTags.length; i++) {
		const metaTag = metaTags[i];
		const metaElement = document.createElement("meta");
		for (const [key, value] of Object.entries(metaTag)) {
			if (!value) {
				console.error(metaTag);
				throw new ReferenceError(`Meta tag must have a value!`);
			}
			metaElement.setAttribute(key, value);
		}
		head.appendChild(metaElement);
	}

	const title = document.createElement("title");
	title.textContent = project.title;
	title.setAttribute("data-i18n", project.titleI18nKey);
	head.appendChild(title);

	const links = [
		["stylesheet", "https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"],
		["stylesheet", "../../css/translations.css"],
		["stylesheet", "../../css/project.css"],
		["shortcut icon", "/images/logo.svg"],
	];

	for (let i = 0; i < links.length; i++) {
		const [rel, href] = links[i];
		const linkElement = document.createElement("link");
		linkElement.setAttribute("rel", rel);
		linkElement.setAttribute("href", href);
		head.appendChild(linkElement);
	}
}

async function insertBodyTags(document, project) {
	const body = document.getElementsByTagName("body")[0];
	body.setAttribute("class", "translating");
	const closeButton = document.createElement("a");
	closeButton.setAttribute("class", "close-button");
	closeButton.setAttribute("href", "../../#portfolio");
	closeButton.textContent = "×"; // &times;
	body.appendChild(closeButton);
	const container = document.createElement("div");
	container.setAttribute("class", "container");
	body.appendChild(container);
	const title = document.createElement("h1");
	title.textContent = project.title;
	title.setAttribute("data-i18n", project.titleI18nKey);
	title.setAttribute("class", "page-title");
	container.appendChild(title);
	/*
	project:
		- title
		- titleI18nKey
		- address
		- addressI18nKey
		- one of:
			- images - a simple array of paths
			- imageGroups - an array of imageGroup objects
			- imageParentGroups - an array of imageGroups objects
	
	imageGroup:
		- pathSegment
		- title
		- titleI18nKey
		- images - a simple array of paths
	
	imageGroups: imageGroup[]
	imageParentGroups: imageGroups[]
	*/
	if (project.imageParentGroups) await insertNestedImageGroups(project.root, container, project.imageParentGroups, "h2", "h3");
	else if (project.imageGroups) await insertImageGroups(project.root, project.root, container, project.imageGroups, "h2");
	else if (project.images) await insertImageList(project.root, container, project.images);
	else {
		throw new Error(`Project "${project.root}" has no images, imageGroups or imageParentGroups.`);
	}

	const translationButton = document.createElement("button");
	translationButton.setAttribute("class", "language-switcher");
	const translationSVG = new DOMParser().parseFromString(`<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 420 420" stroke="currentColor" fill="none" class="language-switcher__icon">
		<path stroke-width="26" d="M209,15a195,195 0 1,0 2,0z"/>
		<path stroke-width="18" d="m210,15v390m195-195H15M59,90a260,260 0 0,0 302,0 m0,240 a260,260 0 0,0-302,0M195,20a250,250 0 0,0 0,382 m30,0 a250,250 0 0,0 0-382"/>
	</svg>`.replaceAll("\n", ""), "text/html").documentElement;
	translationButton.appendChild(translationSVG);
	const translationText = document.createElement("span");
	translationText.textContent = "RU";
	translationText.setAttribute("data-i18n", "language-switcher");
	translationButton.appendChild(translationText);
	body.appendChild(translationButton);

	const scripts = [
		"https://cdn.jsdelivr.net/npm/i18next@26.3.6/dist/umd/i18next.min.js",
		"https://cdn.jsdelivr.net/npm/i18next-browser-languagedetector@8.2.1/dist/umd/i18nextBrowserLanguageDetector.min.js",
		"https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js",
		"../../js/translations.js",
		"../../js/project.js"
	];

	for (let i = 0; i < scripts.length; i++) {
		const script = document.createElement("script");
		script.setAttribute("src", scripts[i]);
		body.appendChild(script);
	}
}

async function insertNestedImageGroups(projectRoot, container, nestedImageGroups, outerTitleTagName, innerTitleTagName) {
	for (let i = 0; i < nestedImageGroups.length; i++) {
		const wrapper = document.createElement("div");
		wrapper.setAttribute("class", "top-level-group-wrapper");
		const title = document.createElement(outerTitleTagName);
		title.textContent = nestedImageGroups[i].title;
		title.setAttribute("data-i18n", nestedImageGroups[i].titleI18nKey);
		title.setAttribute("class", "top-level-group__title");
		wrapper.appendChild(title);

		const list = document.createElement("ul");
		list.setAttribute("class", "top-level-group");
		const item = nestedImageGroups[i];
		await insertImageGroups(`${projectRoot}/${item.pathSegment}`, projectRoot, list, item.imageGroups, innerTitleTagName)

		wrapper.appendChild(list);
		container.appendChild(wrapper);
	}
}

async function insertImageGroups(root, projectRoot, container, imageGroups, titleTagName) {
	const wrapperTag = ["ul", "ol"].includes(container.tagName.toLowerCase()) ? "li" : "div";
	for (let i = 0; i < imageGroups.length; i++) {
		const wrapper = document.createElement(wrapperTag);
		wrapper.setAttribute("class", "image-group");
		const title = document.createElement(titleTagName);
		title.textContent = imageGroups[i].title;
		title.setAttribute("data-i18n", imageGroups[i].titleI18nKey);
		title.setAttribute("class", "image-group__title");
		wrapper.appendChild(title);

		const list = document.createElement("ul");
		list.setAttribute("class", "image-list");
		const item = imageGroups[i];
		await insertImages(`${root}/${item.pathSegment}`, projectRoot, list, item.images, "image-list__item");

		wrapper.appendChild(list);
		container.appendChild(wrapper);
	}
}

async function insertImageList(root, container, images) {
	const list = document.createElement("ul");
	list.setAttribute("class", "image-list");
	await insertImages(root, root, list, images, "image-list__item");
	container.appendChild(list);
}

function findDuplicates(arr) {
	const seen = new Set();
	const duplicates = new Set();

	for (const item of arr) {
		if (seen.has(item)) {
			duplicates.add(item);
		} else {
			seen.add(item);
		}
	}

	return Array.from(duplicates);
}

async function insertImages(root, projectRoot, container, images, liClassName) {
	const duplicates = findDuplicates(images);
	if (duplicates.length > 0) {
		throw new Error(`Duplicate images found: ${duplicates.join(", ")}`);
	}
	const doLiWrap = ["ul", "ol"].includes(container.tagName.toLowerCase());
	console.log(`Trying to process ${images.length} images...`);
	for (let i = 0; i < images.length; i++) {
		console.log(projectRoot, images[i]);
		let toAppend;
		if (doLiWrap) {
			const li = document.createElement("li");
			li.setAttribute("class", liClassName);
			container.appendChild(li);
			toAppend = li;
		} else {
			toAppend = container;
		}

		const optimizedImages = await optimizeImage(root, projectRoot, images[i], 80, [480, 800]);
		const anchor = document.createElement("a");
		anchor.setAttribute("href", optimizedImages.converted);
		anchor.setAttribute("class", "image-link");
		const image = document.createElement("img");
		image.setAttribute("src", optimizedImages.resized[0].path);
		image.setAttribute(
			"srcset",
			optimizedImages.resized
				.map(image => `${image.path} ${image.size}w`)
				.join(", ")
		);
		image.setAttribute(
			"sizes",
			"(max-width: 700px) 100vw, 400px"
		)
		image.setAttribute("alt", "рендер");
		image.setAttribute("class", "image");
		image.setAttribute("loading", "lazy");
		image.setAttribute("decoding", "async");
		anchor.setAttribute("data-fancybox", root);
		anchor.appendChild(image);
		toAppend.appendChild(anchor);
	}
}

function getOutputBaseDir(root) {
	return path.join(import.meta.dirname, `../${root}/${DIST_DIR}`);
}

async function optimizeImage(root, projectRoot, image, quality, sizes) {
	let relativeDir = (root === projectRoot) ? path.dirname(image) : root.replace(projectRoot, "");
	const outputDir = path.join(getOutputBaseDir(projectRoot), relativeDir);
	if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

	const baseName = path.basename(image, path.extname(image));
	const basePath = path.join(import.meta.dirname, `../${root}/${image}`);
	const outputBasePath = `${outputDir}/${baseName}`;
	const outputExt = "webp";
	if (!skipImages) {
		await sharp(basePath).webp({ quality }).toFile(`${outputBasePath}.${outputExt}`);

		for (const size of sizes) {
			await sharp(`${outputBasePath}.${outputExt}`)
				.resize(size, null, { withoutEnlargement: true })
				.webp({ quality })
				.toFile(`${outputBasePath}-${size}.${outputExt}`);
		}
	}

	const relativeDirSlash = (relativeDir && relativeDir !== ".") ? stringEndingWith(relativeDir, "/") : "/";
	// console.log("./", DIST_DIR, relativeDirSlash, baseName, ".", outputExt);
	return {
		converted: `./${DIST_DIR}${relativeDirSlash}${baseName}.${outputExt}`,
		resized: sizes.map(size => ({
			size,
			path: `./${DIST_DIR}${relativeDirSlash}${baseName}-${size}.${outputExt}`
		}))
	};
}

function stringEndingWith(string, ending) {
	return string.endsWith(ending) ? string : `${string}${ending}`;
}